import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { AiModal } from "./AiModal";
import { BodyText } from "@/components/atoms/BodyText";
import { ContentBlock, type ContentBlockItem } from "@/components/molecules/ContentBlock";
import { Button } from "@/components/atoms/Button";

const meta: Meta<typeof AiModal> = {
  title: "AI Modal/AiModal",
  component: AiModal,
  tags: ["autodocs"],
  argTypes: {
    isOpen: {
      control: "boolean",
    },
    headline: {
      control: "text",
    },
  },
  args: {
    isOpen: true,
    headline: "Ask about this portfolio",
  },
  decorators: [
    (Story) => (
      <div style={{ minHeight: "100vh", position: "relative" }}>
        <div className="p-8">
          <h1 className="text-2xl font-bold mb-4">Portfolio Content</h1>
          <p className="mb-4">
            This is some sample content that would be on the page. The modal
            should appear above this content when opened.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </p>
        </div>
        <Story />
      </div>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof AiModal>;

export const DefaultOpen: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
        />
      </>
    );
  },
  args: {
    headline: "ASK ABOUT THIS PORTFOLIO",
    children: (
      <ContentBlock
        headline=""
        items={[
          {
            eyebrow: "AI · Generated Response",
            body: "This is a sample AI response. In a real implementation, this would be generated by the AI system based on the user's question. The modal provides a focused space for conversational exploration of the portfolio content.",
            isAI: true,
          },
          {
            eyebrow: "AI · Generated Response",
            body: "Users can ask questions, get detailed explanations, and navigate to specific sections. The system uses RAG (Retrieval Augmented Generation) to provide contextually relevant answers based on the portfolio content.",
            isAI: true,
          },
        ]}
        headlineVariant="display"
        headlineClassName="hidden"
        eyebrowClassName="w-full md:w-[7.25rem]"
        bodyClassName="max-w-[24.25rem]"
      />
    ),
  },
};

export const LongContent: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
        />
      </>
    );
  },
  args: {
    headline: "ASK ABOUT THIS PORTFOLIO",
    children: (
      <ContentBlock
        headline=""
        items={Array.from({ length: 10 }, (_, i) => ({
          eyebrow: "AI · Generated Response",
          body: `This is paragraph ${i + 1} of a long response. The modal card should scroll internally while the backdrop remains fixed. This demonstrates that the max-h-[70vh] constraint and overflow-y-auto are working correctly. The content should be scrollable within the card, and the overlay should remain in place. This ensures users can read through extended AI responses without the modal taking up the entire screen.`,
          isAI: true,
        }))}
        headlineVariant="display"
        headlineClassName="hidden"
        eyebrowClassName="w-full md:w-[7.25rem]"
        bodyClassName="max-w-[24.25rem]"
      />
    ),
  },
};

export const WithoutHeadline: Story = {
  args: {
    isOpen: true,
    headline: undefined,
    children: (
      <div className="space-y-4">
        <BodyText body="This modal has no headline, demonstrating the component's flexibility." />
      </div>
    ),
  },
};

export const Closed: Story = {
  args: {
    isOpen: false,
    headline: "Ask about this portfolio",
    children: (
      <div className="space-y-4">
        <BodyText body="This modal is closed and should not be visible." />
      </div>
    ),
  },
};

