import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { AiModal } from "./AiModal";
import { AiConversationRow } from "./AiConversationRow";
import { AiActionsRow, type AiAction } from "./AiActionsRow";
import { Composer } from "@/components/molecules/Composer";
import { BodyText } from "@/components/atoms/BodyText";
import { Button } from "@/components/atoms/Button";

const meta: Meta<typeof AiModal> = {
  title: "AI Modal/AiModal",
  component: AiModal,
  tags: ["autodocs"],
  argTypes: {
    isOpen: {
      control: "boolean",
    },
    headline: {
      control: "text",
    },
  },
  args: {
    isOpen: true,
    headline: "Ask about this portfolio",
  },
  decorators: [
    (Story) => (
      <div style={{ minHeight: "100vh", position: "relative" }}>
        <div className="p-8">
          <h1 className="text-2xl font-bold mb-4">Portfolio Content</h1>
          <p className="mb-4">
            This is some sample content that would be on the page. The modal
            should appear above this content when opened.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </p>
        </div>
        <Story />
      </div>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof AiModal>;

export const DefaultOpen: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={() => (
            <>
              <AiConversationRow
                role="ai"
                body="This is a sample AI response. In a real implementation, this would be generated by the AI system based on the user's question. The modal provides a focused space for conversational exploration of the portfolio content."
              />
              <AiConversationRow
                role="ai"
                body="Users can ask questions, get detailed explanations, and navigate to specific sections. The system uses RAG (Retrieval Augmented Generation) to provide contextually relevant answers based on the portfolio content."
              />
            </>
          )}
        />
      </>
    );
  },
  args: {
    headline: "ASK ABOUT THIS PORTFOLIO",
  },
};

export const ConversationWithActions: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    
    const handleActionClick = (action: AiAction) => {
      console.log("Action clicked:", action);
      alert(`Action clicked: ${action.label}`);
    };

    const sampleActions: AiAction[] = [
      { type: "navigate", label: "View Capital One case study", target: "/work/capital-one" },
      { type: "scroll", label: "See my design process", target: "design-process" },
      { type: "deep_dive", label: "Tell me about your role", topic: "role-description" },
    ];

    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={() => (
            <>
              <AiConversationRow
                role="user"
                body="Can you tell me more about your recent work?"
              />
              <AiConversationRow
                role="ai"
                body="I'd be happy to share more about my recent projects! I've been focused on creating elegant, user-centered digital experiences. My work spans from consumer banking interfaces to creative technology installations."
              />
            </>
          )}
          renderActions={() => (
            <AiActionsRow
              actions={sampleActions}
              onActionClick={handleActionClick}
            />
          )}
        />
      </>
    );
  },
  args: {
    headline: "ASK ABOUT THIS PORTFOLIO",
  },
};

export const LongConversationWithActions: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    
    const handleActionClick = (action: AiAction) => {
      console.log("Action clicked:", action);
      alert(`Action clicked: ${action.label}`);
    };

    const sampleActions: AiAction[] = [
      { type: "navigate", label: "View full portfolio", target: "/work" },
      { type: "scroll", label: "Jump to contact", target: "contact" },
      { type: "deep_dive", label: "Learn about my process", topic: "design-process" },
      { type: "navigate", label: "See case studies", target: "/work" },
    ];

    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={() => (
            <>
              <AiConversationRow
                role="user"
                body="What makes your approach to UX design unique?"
              />
              <AiConversationRow
                role="ai"
                body="My approach combines editorial minimalism with a deep focus on user research. I believe that great design should be invisible—it should guide users naturally without drawing attention to itself."
              />
              <AiConversationRow
                role="user"
                body="Can you give me an example from a recent project?"
              />
              <AiConversationRow
                role="ai"
                body="Absolutely. In the Capital One Travel project, we redesigned the entire booking experience. The challenge was to simplify a complex multi-step flow while maintaining user confidence and reducing cognitive load. We achieved a 40% increase in completion rates by focusing on progressive disclosure and clear hierarchy."
              />
              <AiConversationRow
                role="ai"
                body="The key insight was understanding that users don't want to think about the interface—they want to focus on planning their trip. So we stripped away unnecessary chrome, used generous white space, and ensured every interaction felt purposeful."
              />
              <AiConversationRow
                role="user"
                body="That's impressive. What tools did you use?"
              />
              <AiConversationRow
                role="ai"
                body="The project leveraged Figma for design, React and TypeScript for implementation, and we built a comprehensive design system to ensure consistency across the platform. We also conducted extensive usability testing throughout the process."
              />
            </>
          )}
          renderActions={() => (
            <AiActionsRow
              actions={sampleActions}
              onActionClick={handleActionClick}
            />
          )}
        />
      </>
    );
  },
  args: {
    headline: "ASK ABOUT THIS PORTFOLIO",
  },
};

export const WithoutHeadline: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={() => (
            <AiConversationRow
              role="ai"
              body="This modal has no headline, demonstrating the component's flexibility."
            />
          )}
        />
      </>
    );
  },
  args: {
    headline: undefined,
  },
};

export const Closed: Story = {
  args: {
    isOpen: false,
    headline: "Ask about this portfolio",
    renderBody: () => (
      <AiConversationRow
        role="ai"
        body="This modal is closed and should not be visible."
      />
    ),
  },
};

export const ConversationWithComposer: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    const [composerValue, setComposerValue] = React.useState("");
    const [messages, setMessages] = React.useState([
      { role: "user" as const, body: "Tell me about your RAG system." },
      { role: "ai" as const, body: "Here's a high-level overview of the RAG pipeline: it combines retrieval from a vector database with language model generation to provide contextually relevant answers based on the portfolio content." },
    ]);

    const handleSubmit = React.useCallback((query: string) => {
      const trimmed = query.trim();
      if (!trimmed) return;
      
      // Add user message
      setMessages((prev) => [
        ...prev,
        { role: "user" as const, body: trimmed },
      ]);
      
      // Simulate AI response after a brief delay (demo only)
      setTimeout(() => {
        setMessages((prev) => [
          ...prev,
          { role: "ai" as const, body: `This is a simulated response to: "${trimmed}". In production, this would be generated by the AI system.` },
        ]);
      }, 1000);
    }, []);

    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={() => (
            <>
              {messages.map((msg, index) => (
                <AiConversationRow
                  key={index}
                  role={msg.role}
                  body={msg.body}
                />
              ))}
            </>
          )}
          renderComposer={() => (
            <Composer
              placeholder="Ask a follow-up question…"
              onSubmit={handleSubmit}
            />
          )}
        />
      </>
    );
  },
  args: {
    headline: "ASK ABOUT THIS PORTFOLIO",
  },
};

export const ComposerOnly: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    const [messages, setMessages] = React.useState<Array<{ role: "user" | "ai"; body: string }>>([]);

    const handleSubmit = React.useCallback((query: string) => {
      const trimmed = query.trim();
      if (!trimmed) return;
      
      // Add user message
      setMessages((prev) => [
        ...prev,
        { role: "user" as const, body: trimmed },
      ]);
      
      // Simulate AI response after a brief delay (demo only)
      setTimeout(() => {
        setMessages((prev) => [
          ...prev,
          { role: "ai" as const, body: `This is a simulated response to: "${trimmed}"` },
        ]);
      }, 1000);
    }, []);

    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={messages.length > 0 ? () => (
            <>
              {messages.map((msg, index) => (
                <AiConversationRow
                  key={index}
                  role={msg.role}
                  body={msg.body}
                />
              ))}
            </>
          ) : undefined}
          renderComposer={() => (
            <Composer
              placeholder="Ask your first question…"
              onSubmit={handleSubmit}
            />
          )}
        />
      </>
    );
  },
  args: {
    headline: "ASK ABOUT THIS PORTFOLIO",
  },
};
