import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { AlertCircle } from "lucide-react";
import { AiModal } from "./AiModal";
import { AiConversationRow, type AiConversationRowProps } from "./AiConversationRow";
import { AiActionsRow, type AiModalAction } from "./AiActionsRow";
import { AiModalProvider, useAiModal } from "./AiModalContext";
import { Composer } from "@/components/molecules/Composer";
import { TypingIndicator } from "@/components/ui/TypingIndicator";
import { BodyText } from "@/components/atoms/BodyText";
import { Button } from "@/components/atoms/Button";

const meta: Meta<typeof AiModal> = {
  title: "AI Modal/AiModal",
  component: AiModal,
  tags: ["autodocs"],
  argTypes: {
    isOpen: {
      control: "boolean",
    },
    headline: {
      control: "text",
    },
  },
  args: {
    isOpen: true,
    headline: "",
  },
  decorators: [
    (Story) => (
      <div style={{ minHeight: "100vh", position: "relative" }}>
        <div className="p-8">
          <h1 className="text-2xl font-bold mb-4">Portfolio Content</h1>
          <p className="mb-4">
            This is some sample content that would be on the page. The modal
            should appear above this content when opened.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </p>
        </div>
        <Story />
      </div>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof AiModal>;

export const DefaultOpen: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={() => (
            <>
              <AiConversationRow
                role="ai"
                body="This is a sample AI response. In a real implementation, this would be generated by the AI system based on the user's question. The modal provides a focused space for conversational exploration of the portfolio content."
              />
              <AiConversationRow
                role="ai"
                body="Users can ask questions, get detailed explanations, and navigate to specific sections. The system uses RAG (Retrieval Augmented Generation) to provide contextually relevant answers based on the portfolio content."
              />
            </>
          )}
        />
      </>
    );
  },
  args: {
    headline: "",
  },
};

export const ConversationWithActions: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    
    const handleActionClick = (action: AiModalAction) => {
      console.log("Action clicked:", action);
      alert(`Action clicked: ${action.label}`);
    };

    const sampleActions: AiModalAction[] = [
      { type: "navigate", label: "View Capital One case study", targetPath: "/work/capital-one" },
      { type: "scroll", label: "See my design process", targetSectionId: "design-process" },
      { type: "suggest_question", label: "Tell me about your role", suggestedQuestion: "What was your role in this project?" },
    ];

    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={() => (
            <>
              <AiConversationRow
                role="user"
                body="Can you tell me more about your recent work?"
              />
              <AiConversationRow
                role="ai"
                body="I'd be happy to share more about my recent projects! I've been focused on creating elegant, user-centered digital experiences. My work spans from consumer banking interfaces to creative technology installations."
              />
            </>
          )}
          renderActions={() => (
            <AiActionsRow
              actions={sampleActions}
              onActionClick={handleActionClick}
            />
          )}
        />
      </>
    );
  },
  args: {
    headline: "",
  },
};

export const LongConversationWithActions: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    
    const handleActionClick = (action: AiModalAction) => {
      console.log("Action clicked:", action);
      alert(`Action clicked: ${action.label}`);
    };

    const sampleActions: AiModalAction[] = [
      { type: "navigate", label: "View full portfolio", targetPath: "/work" },
      { type: "scroll", label: "Jump to contact", targetSectionId: "contact" },
      { type: "suggest_question", label: "Learn about my process", suggestedQuestion: "Can you tell me more about your design process?" },
      { type: "navigate", label: "See case studies", targetPath: "/work" },
    ];

    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={() => (
            <>
              <AiConversationRow
                role="user"
                body="What makes your approach to UX design unique?"
              />
              <AiConversationRow
                role="ai"
                body="My approach combines editorial minimalism with a deep focus on user research. I believe that great design should be invisible—it should guide users naturally without drawing attention to itself."
              />
              <AiConversationRow
                role="user"
                body="Can you give me an example from a recent project?"
              />
              <AiConversationRow
                role="ai"
                body="Absolutely. In the Capital One Travel project, we redesigned the entire booking experience. The challenge was to simplify a complex multi-step flow while maintaining user confidence and reducing cognitive load. We achieved a 40% increase in completion rates by focusing on progressive disclosure and clear hierarchy."
              />
              <AiConversationRow
                role="ai"
                body="The key insight was understanding that users don't want to think about the interface—they want to focus on planning their trip. So we stripped away unnecessary chrome, used generous white space, and ensured every interaction felt purposeful."
              />
              <AiConversationRow
                role="user"
                body="That's impressive. What tools did you use?"
              />
              <AiConversationRow
                role="ai"
                body="The project leveraged Figma for design, React and TypeScript for implementation, and we built a comprehensive design system to ensure consistency across the platform. We also conducted extensive usability testing throughout the process."
              />
            </>
          )}
          renderActions={() => (
            <AiActionsRow
              actions={sampleActions}
              onActionClick={handleActionClick}
            />
          )}
        />
      </>
    );
  },
  args: {
    headline: "",
  },
};

export const WithoutHeadline: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={() => (
            <AiConversationRow
              role="ai"
              body="This modal has no headline, demonstrating the component's flexibility."
            />
          )}
        />
      </>
    );
  },
  args: {
    headline: undefined,
  },
};

export const Closed: Story = {
  args: {
    isOpen: false,
    headline: "",
    renderBody: () => (
      <AiConversationRow
        role="ai"
        body="This modal is closed and should not be visible."
      />
    ),
  },
};

export const ConversationWithComposer: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    const [composerValue, setComposerValue] = React.useState("");
    const [messages, setMessages] = React.useState([
      { role: "user" as const, body: "Tell me about your RAG system." },
      { role: "ai" as const, body: "Here's a high-level overview of the RAG pipeline: it combines retrieval from a vector database with language model generation to provide contextually relevant answers based on the portfolio content." },
    ]);

    const handleSubmit = React.useCallback((query: string) => {
      const trimmed = query.trim();
      if (!trimmed) return;
      
      // Add user message
      setMessages((prev) => [
        ...prev,
        { role: "user" as const, body: trimmed },
      ]);
      
      // Simulate AI response after a brief delay (demo only)
      setTimeout(() => {
        setMessages((prev) => [
          ...prev,
          { role: "ai" as const, body: `This is a simulated response to: "${trimmed}". In production, this would be generated by the AI system.` },
        ]);
      }, 1000);
    }, []);

    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={() => (
            <>
              {messages.map((msg, index) => (
                <AiConversationRow
                  key={index}
                  role={msg.role}
                  body={msg.body}
                />
              ))}
            </>
          )}
          renderComposer={() => (
            <Composer
              placeholder="Ask a follow-up question…"
              onSubmit={handleSubmit}
            />
          )}
        />
      </>
    );
  },
  args: {
    headline: "",
  },
};

export const ComposerOnly: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);
    const [messages, setMessages] = React.useState<Array<{ role: "user" | "ai"; body: string }>>([]);

    const handleSubmit = React.useCallback((query: string) => {
      const trimmed = query.trim();
      if (!trimmed) return;
      
      // Add user message
      setMessages((prev) => [
        ...prev,
        { role: "user" as const, body: trimmed },
      ]);
      
      // Simulate AI response after a brief delay (demo only)
      setTimeout(() => {
        setMessages((prev) => [
          ...prev,
          { role: "ai" as const, body: `This is a simulated response to: "${trimmed}"` },
        ]);
      }, 1000);
    }, []);

    return (
      <>
        <div className="p-8">
          <Button onClick={() => setIsOpen(true)} variant="primary">
            Open AI Modal
          </Button>
        </div>
        <AiModal
          {...args}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          renderBody={messages.length > 0 ? () => (
            <>
              {messages.map((msg, index) => (
                <AiConversationRow
                  key={index}
                  role={msg.role}
                  body={msg.body}
                />
              ))}
            </>
          ) : undefined}
          renderComposer={() => (
            <Composer
              placeholder="Ask your first question…"
              onSubmit={handleSubmit}
            />
          )}
        />
      </>
    );
  },
  args: {
    headline: "",
  },
};

// ============================================================
// STATE MACHINE DEMO STORY
// ============================================================

/**
 * StateMachineDemo - Demonstrates the AiModalProvider + useAiModal() hook
 * 
 * This story showcases:
 * - State machine lifecycle (opening, thinking, answer_showing, etc.)
 * - "Replace while open" behavior for new open events
 * - Error handling with inline error display
 * - Messages and actions managed externally (not in state machine)
 * 
 * NOTE: This is demo-only logic for Storybook, not production AI.
 */
const StateMachineDemoInner = () => {
  // External message and action state (NOT in state machine)
  const [messages, setMessages] = React.useState<AiConversationRowProps[]>([
    { role: "user", body: "Tell me about your RAG system." },
    { role: "ai", body: "Here's a high-level overview of the RAG pipeline..." },
  ]);
  
  const [actions, setActions] = React.useState<AiModalAction[]>([
    { type: "navigate", label: "View case studies", targetPath: "/work" },
    { type: "scroll", label: "See process", targetSectionId: "process" },
  ]);

  // Get state machine hooks
  const {
    state,
    isOpen,
    isThinking,
    hasError,
    openFromSelection,
    openGlobal,
    submitQuestion,
    markAnswerReceived,
    setError,
    clearError,
    close,
  } = useAiModal();

  // Handle submission from Composer
  const handleComposerSubmit = React.useCallback(
    (query: string) => {
      const trimmed = query.trim();
      if (!trimmed) return;

      // 1. Tell state machine we submitted
      submitQuestion({ question: trimmed });

      // 2. Update local messages (external to state machine)
      setMessages((prev) => [...prev, { role: "user", body: trimmed }]);

      // 3. Simulate async AI answer (demo only)
      setTimeout(() => {
        setMessages((prev) => [
          ...prev,
          {
            role: "ai",
            body: `This is a simulated AI response to: "${trimmed}". In production, this would be generated by the RAG pipeline.`,
          },
        ]);

        // 4. Notify state machine that answer has been received
        markAnswerReceived();
      }, 800);
    },
    [submitQuestion, markAnswerReceived]
  );

  // Handle "Open from selection" - demonstrates replace-while-open
  const handleOpenSelection = React.useCallback(() => {
    // Clear local messages/actions (external state)
    setMessages([
      {
        role: "ai",
        body: "I see you've selected some text. This demonstrates the 'replace while open' behavior. The modal stays open but context changes.",
      },
    ]);
    setActions([
      { type: "suggest_question", label: "Explore this section", suggestedQuestion: "Can you tell me more about this section?" },
    ]);

    // Tell state machine to open from selection
    openFromSelection({
      selectedText: "This is the selected text from the page...",
      headline: "Ask about this section",
    });
  }, [openFromSelection]);

  // Handle "Open global" - demonstrates replace-while-open
  const handleOpenGlobal = React.useCallback(() => {
    // Clear local messages/actions (external state)
    setMessages([
      {
        role: "ai",
        body: "Welcome! This is the global AI assistant. Ask me anything about the portfolio.",
      },
    ]);
    setActions([
      { type: "navigate", label: "View all projects", targetPath: "/work" },
      { type: "scroll", label: "Jump to about", targetSectionId: "about" },
    ]);

    // Tell state machine to open global with section context
    openGlobal({
      headline: "",
      source: "hover-pill",
      selectedText: "This is a generative portfolio powered by AI agents. It uses RAG to retrieve relevant project information and render custom layouts for each case study. The system includes an orchestrator agent that generates PageJSON and a copywriter agent that creates editorial content.",
    });
  }, [openGlobal]);

  // Handle "Trigger Error" button
  const handleTriggerError = React.useCallback(() => {
    setError("This is a simulated error message. It demonstrates inline error display.");
  }, [setError]);

  // Handle action clicks
  const handleActionClick = React.useCallback((action: AiModalAction) => {
    console.log("Action clicked:", action);
    alert(`Action clicked: ${action.label}`);
  }, []);

  return (
    <div className="p-8">
      {/* Demo Controls */}
      <div className="mb-8 space-y-4">
        <h2 className="text-2xl font-bold mb-4">State Machine Demo</h2>
        
        <div className="flex flex-wrap gap-3">
          <Button onClick={handleOpenSelection} variant="primary">
            Open from selection
          </Button>
          <Button onClick={handleOpenGlobal} variant="secondary">
            Open global AI modal
          </Button>
          <Button onClick={handleTriggerError} variant="destructive">
            Trigger Error
          </Button>
          {hasError && (
            <Button onClick={clearError} variant="outline">
              Clear Error
            </Button>
          )}
        </div>
      </div>

      {/* Floating State Display - Always visible on top */}
      <div className="fixed top-4 right-4 z-[60] p-4 bg-white border-2 border-gray-300 rounded-lg shadow-lg max-w-sm">
        <h3 className="font-bold mb-2 text-sm">Current State:</h3>
        <pre className="text-xs overflow-auto max-h-[300px]">
          {JSON.stringify(
            {
              status: state.status,
              isOpen: state.isOpen,
              source: state.source,
              headline: state.headline,
              hasSelectedText: !!state.selectedText,
              lastQuestion: state.lastQuestion,
              hasError: hasError,
            },
            null,
            2
          )}
        </pre>
      </div>

      {/* AI Modal */}
      <AiModal
        isOpen={isOpen}
        onClose={close}
        headline={state.headline ?? undefined}
        renderBody={() => (
          <>
            {/* Show selected text if present */}
            {state.selectedText && (
              <AiConversationRow
                role="user"
                eyebrowLabel="Selected text"
                body={state.selectedText}
              />
            )}

            {/* Show messages (managed externally) */}
            {messages.map((msg, index) => (
              <AiConversationRow
                key={msg.id ?? index}
                role={msg.role}
                body={msg.body}
                eyebrowLabel={msg.eyebrowLabel}
              />
            ))}

            {/* Show thinking state */}
            {isThinking && messages.length > 0 && messages[messages.length - 1].role === "user" && (
              <AiConversationRow
                role="ai"
                eyebrowLabel="AI"
                body={<TypingIndicator label="" />}
              />
            )}

            {/* Show error state */}
            {hasError && state.errorMessage && (
              <AiConversationRow
                role="ai"
                eyebrowLabel="AI"
                body={
                  <span className="inline-flex items-baseline gap-2">
                    <AlertCircle className="w-4 h-4 opacity-60" />
                    {state.errorMessage}
                  </span>
                }
              />
            )}
          </>
        )}
        renderActions={
          actions.length > 0
            ? () => <AiActionsRow actions={actions} onActionClick={handleActionClick} />
            : undefined
        }
        renderComposer={() => (
          <Composer
            placeholder="Ask a question…"
            onSubmit={handleComposerSubmit}
            hideStatus={true}
          />
        )}
      />
    </div>
  );
};

export const WithSystemMessage: Story = {
  render: (args) => {
    const [isOpen, setIsOpen] = React.useState(true);

    return (
      <AiModal
        isOpen={isOpen}
        onClose={() => setIsOpen(false)}
        headline="ASK ABOUT THE TANGER CASE STUDY"
        renderBody={() => (
          <>
            <AiConversationRow
              role="system"
              eyebrowLabel="System"
              body="You're now asking about the Tanger case study. I can help you understand the problem, solution, tech stack, or outcomes."
            />
            <AiConversationRow
              role="user"
              eyebrowLabel="You"
              body="What technologies did you use in this project?"
            />
            <AiConversationRow
              role="ai"
              eyebrowLabel="AI"
              body="For the Tanger project, I worked with React, TypeScript, Next.js, and Tailwind CSS. The backend used Node.js with Express, and we integrated with the Tanger Outlets API for real-time data."
            />
          </>
        )}
        renderActions={() => (
          <AiActionsRow
            actions={[
              { type: "scroll", label: "Scroll to Tech Stack", targetSectionId: "tech-stack" },
              { type: "suggest_question", label: "Ask about outcomes", suggestedQuestion: "What were the key outcomes of this project?" },
            ]}
            onActionClick={(action) => {
              console.log("Action clicked:", action);
            }}
          />
        )}
        renderComposer={() => (
          <Composer
            placeholder="Ask about this project…"
            onSubmit={(query) => console.log("Submitted:", query)}
          />
        )}
      />
    );
  },
  args: {},
};

export const StateMachineDemo: Story = {
  render: () => (
    <AiModalProvider>
      <StateMachineDemoInner />
    </AiModalProvider>
  ),
  args: {},
  parameters: {
    // Disable default decorators for this story
    layout: "fullscreen",
  },
};
